#!/bin/bash
#***************************************************
#脚本：MAIL_SYS
#编写：zjhou
#日期：2015-11-15
#描述：mail_utils_wraper
#备注：
#***************************************************

#删除邮件
# $*     邮件序号
del_mail() {
	mail << EOF
	d $*
EOF
}

#提取邮件主题（不支持空格）
# $1     邮件序号
get_mail_subj() {
	local subj=`mail -H | awk '{if($1 == "'$1'") print $3}'`
	echo $subj
}

#如果收件箱有黑名单中的邮件则删除它
#-------------------------
# 参数   描述
#  $1     黑名单文件，
#         每行一个黑名单地址关键字
#-------------------------
del_ad_mail() {
	local target_num=(`mail -H | grep -f $1 | awk '{print $1}'`)

	if [ -z $target_num ]; then
		return 1	
	else
		del_mail ${target_num[@]}
		return 0
	fi
}

#检测邮件是否带有附件。
#$1 邮件序号
has_attach?() {
	{
		mail << EOF
			p $1
			q
EOF
	#有关键词"Part 2:"则除了正文部分还有附件。
	} | grep "^Part 2:$" > /dev/null
	return $?
}

#获取邮件正文
#$1 邮件序号
get_mail_text() {

	if has_attach? $1; then
		local cutline="Part 2:"
	else
		local cutline="-end-"
	fi

	{
		mail << EOF
		p $1
		echo " "
		echo $cutline
		q
EOF
	} | sed -n "/Content-Type: text\/plain/, /$cutline/p" \
	  | sed '1,2d;$d;' 
}

#获取邮件附件
#$1 邮件序号
#$2 附件存放文件夹
#返回值 附件名单
#副作用 将附件解压到指定文件夹
get_mail_attach() {

	cd /var/tmp
	if ! is_dir_empty? .; then
		rm /var/tmp/*
	fi

	{
		mail << EOF
		copy $1 mail_with_attach.txt
		q
EOF
	} &> /dev/null

	munpack  mail_with_attach.txt &> /dev/null && \
	rm mail_with_attach.txt

	ls -rt *
	mv /var/tmp/* $2
}
